WITH CTE AS (SELECT SUM(ORDER_ITEMS.PRICE) TOTAL_SUM, 
PRODUCTS.PRODUCT_CATEGORY_NAME, EXTRACT(WEEK FROM ORDER_PURCHASE_TIMESTAMP) WEEK
                    FROM TAKE_HOME_CHALLENGE.ECOMMERCE.ORDERS ORDERS
                    LEFT JOIN TAKE_HOME_CHALLENGE.ECOMMERCE.ORDER_ITEMS ORDER_ITEMS
                    ON ORDERS.ORDER_ID=ORDER_ITEMS.ORDER_ID
                    LEFT JOIN TAKE_HOME_CHALLENGE.ECOMMERCE.PRODUCTS PRODUCTS
                    ON ORDER_ITEMS.PRODUCT_ID=PRODUCTS.PRODUCT_ID                 
GROUP BY PRODUCTS.PRODUCT_CATEGORY_NAME, WEEK
ORDER BY WEEK),
TOP_3_PRODUCTS AS (
SELECT SUM(ORDER_ITEMS.PRICE) SALES, PRODUCTS.PRODUCT_CATEGORY_NAME 
FROM TAKE_HOME_CHALLENGE.ECOMMERCE.ORDERS ORDERS
                    LEFT JOIN TAKE_HOME_CHALLENGE.ECOMMERCE.ORDER_ITEMS ORDER_ITEMS
                    ON ORDERS.ORDER_ID=ORDER_ITEMS.ORDER_ID
                    LEFT JOIN TAKE_HOME_CHALLENGE.ECOMMERCE.PRODUCTS PRODUCTS
                    ON ORDER_ITEMS.PRODUCT_ID=PRODUCTS.PRODUCT_ID
WHERE EXTRACT(MONTH FROM ORDER_PURCHASE_TIMESTAMP) = 11 AND EXTRACT(YEAR FROM ORDER_PURCHASE_TIMESTAMP) =2017
GROUP BY PRODUCTS.PRODUCT_CATEGORY_NAME
ORDER BY SALES DESC
LIMIT 3
),
GMV_TABLE AS (SELECT SUM (TOTAL_SUM) OVER (PARTITION BY CTE.PRODUCT_CATEGORY_NAME ORDER BY WEEK) GMV, WEEK, CTE.PRODUCT_CATEGORY_NAME 
FROM CTE
INNER JOIN TOP_3_PRODUCTS
ON TOP_3_PRODUCTS.PRODUCT_CATEGORY_NAME= CTE.PRODUCT_CATEGORY_NAME)
SELECT *, (GMV-LAG(GMV) OVER (PARTITION BY PRODUCT_CATEGORY_NAME ORDER BY WEEK))/ LAG(GMV) OVER (PARTITION BY PRODUCT_CATEGORY_NAME ORDER BY WEEK) *100 GROWTH_RATE
FROM GMV_TABLE